# Generated by Django 5.2.3 on 2025-07-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='pdf_path',
            field=models.FilePathField(blank=True, null=True, path='media/cv_pdfs'),
        ),
    ]
