# Generated by Django 5.2.3 on 2025-07-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cv_pdf_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pdf_path',
            field=models.FileField(blank=True, null=True, upload_to='cv_pdfs/'),
        ),
    ]
