# Generated by Django 5.2.3 on 2025-07-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_cv_pdf_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='pdf_path',
            new_name='pdf_file',
        ),
    ]
